name: CI -> Test
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup development dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun run test

# TODO: Track IINFRA-501
#      - name: Upload coverage
#        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          coverage-reports: coverage/lcov.*