name: CI -> Test
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup development dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun run test

# TODO: Track IINFRA-501
#      - name: Upload coverage
#        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          coverage-reports: coverage/lcov.*